### ISSUE TITLE
Mod prevents you from Unsheathing

### ISSUE THREAD

**Issue by Mfunn** [HSValhiem/HS_EquipInWater#5]
When you use the Hide/show weapon keybind, you can sheath your weapons / tools / shields in the back of the character but this mod prevents you from unsheathing them when pressing the same keybind.

I've tested it by only disabling your mod = unsheathing works, putting it back on = unsheathing broken

It would be a shame to use UseEquipmentInWater instead because of this bug since your mod looks more optimized.

**Comment by vitalikbyrevich** [comment]
I confirm the presence of this error. I can't equip my weapons back/ shield when pressing R. I remove the mod - and again I can equip weapons with one button.

**Comment by SaltSouls** [comment]
Yup, also getting this problem. Unfortunately it kinda looks like the mod is dead as there has been 0 activity on it in about three months.

**Comment by safisynai** [comment]
I had a quick look just now and figured out what was wrong (one of the patches was NOPing the wrong instructions for the current build of the game). Submitted a PR that fixes this :)

**Comment by chrisjenda** [comment]
Resolved in Update 0.1.7 Thank you for Bringing this to our attention @Mfunn @SaltSouls @vitalikbyrevich and thanks @safisynai for the Temporary fix while HS was away from the scene!
